#!/bin/sh

SUNDIALS_ROOT=`realpath ./sundials`
SUNDIALS_URL=" https://github.com/LLNL/sundials/releases/download/v6.2.0/sundials-6.2.0.tar.gz"

rm -rf $SUNDIALS_ROOT
mkdir $SUNDIALS_ROOT

cd $SUNDIALS_ROOT
wget $SUNDIALS_URL

tar xzf sundials-6.2.0.tar.gz
mkdir build;
cd build;
cmake ../sundials-6.2.0/ -DCMAKE_INSTALL_PREFIX=$SUNDIALS_ROOT -DBUILD_EXAMPLES=off -DEXAMPLES_INSTALL=off;
make -j install;

echo
echo
echo "Sundials has been compiled. To make MCTrans++ you should add"
echo " SUNDIALS_DIR=$SUNDIALS_ROOT"
echo "in Makefile.local"
echo
echo
