include Makefile.local

CXX ?= g++

STD=c++20

ifdef DEBUG
CXXFLAGS += -DDEBUG -g3 -O0 --std=$(STD) -Werror -pedantic
else
CXXFLAGS += -O3 -march=native --std=$(STD) -Wall
endif

SUNDIALS_DIR ?= /usr/local

SUNDIALS_INC ?=$(realpath $(SUNDIALS_DIR)/include)
SUNDIALS_LIB ?=$(realpath $(SUNDIALS_DIR)/lib)

ifeq ($(strip $(SUNDIALS_INC)),)
$(error "Sundials include directory not found at $(SUNDIALS_DIR)/include")
endif

ifeq ($(strip $(SUNDIALS_LIB)),)
$(error "Sundials compiled library directory not found at $(SUNDIALS_DIR)/lib")
endif

SUNFLAGS=-I$(SUNDIALS_INC)
SUN_LINK_FLAGS = -L$(SUNDIALS_LIB) -Wl,-rpath $(SUNDIALS_LIB) -lsundials_arkode -lsundials_nvecserial

TOML11_DIR ?= ./toml11
TOML_FLAGS = -I$(realpath $(TOML11_DIR))

CXXFLAGS += $(TOML_FLAGS) $(SUNFLAGS)

ifdef BOOST_DIR
	BOOST_FLAGS = -I$(realpath $(BOOST_DIR))
	CXXFLAGS += $(BOOST_FLAGS)
endif

NETCDF_LINK_FLAGS =

ifdef NETCDF_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_DIR))/include
	NETCDF_LINK_FLAGS = -L$(realpath $(NETCDF_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_DIR))/lib
ifndef NETCDF_CXX_DIR
	NETCDF_CXX_DIR = $(NETCDF_DIR)
endif
endif

ifdef NETCDF_CXX_DIR
	CXXFLAGS += -I$(realpath $(NETCDF_CXX_DIR))/include
	NETCDF_LINK_FLAGS += -L$(realpath $(NETCDF_CXX_DIR))/lib -Wl,-rpath $(realpath $(NETCDF_CXX_DIR))/lib
endif
	
ifndef NETCDF_CXX_LIB
	NETCDF_LINK_FLAGS += -lnetcdf -lnetcdf_c++4
else
	NETCDF_LINK_FLAGS += -lnetcdf -l$(NETCDF_CXX_LIB)
endif

Makefile.local:
	$(error You need to provide a Makefile.local for your machine. Try copying Makefile.local.example)


