#!/bin/bash

MCTRANS=../MCTrans++


function test_case {
	local INPUT="$CASE.conf"
	local OUTPUT="$CASE.out"
	local REF="$CASE.report"
	$MCTRANS $INPUT > $OUTPUT
	diff -q $OUTPUT $REF && echo "Reference input $CASE.conf produces expected output";
	rm -f $OUTPUT;
}

CASES=(Mirror_1keV Mirror_100kV Breakeven)

for CASE in ${CASES[@]}; do
	test_case
done
