
MCTrans.pdf: MCTrans.pdf macros.tex references.bib
	pdflatex MCTrans
	pdflatex MCTrans
	bibtex MCTrans
	pdflatex MCTrans

clean:
	rm -f MCTrans.pdf MCTrans.out MCTrans.log MCTrans.bbl MCTrans.blg MCTrans.aux macros.aux
